# Generated by Django 3.0.8 on 2020-08-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
