# Generated by Django 3.0.8 on 2020-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200810_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Start price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(verbose_name='Listing Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(default='https://www.freeiconspng.com/uploads/no-image-icon-4.png', help_text='enter an optional image link for your listing', verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Listing Title'),
        ),
    ]
