# Generated by Django 3.0.8 on 2020-08-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200812_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='seller',
        ),
    ]
