# Generated by Django 3.0.8 on 2020-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200812_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='currentPrice',
            new_name='initialPrice',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Leave a comment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(blank=True, help_text='if no value is put a default value will be assigned', verbose_name='Image Link'),
        ),
    ]
