name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          export SECRET_KEY="justforgithubenv"
          export ALLOWED_HOSTS=".localhost, .herokuapp.com"
          pip3 install --user setuptools
          pip3 install --user -r requirements.txt
          python3 manage.py test
